# Generated by Django 2.2.6 on 2019-10-20 19:57

from django.db import migrations, models
import django.utils.timezone
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('lookspace_app', '0002_bookedseats'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=64, null=True)),
                ('email', models.EmailField(max_length=128, null=True)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('comapny_name', models.CharField(max_length=64, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
