# Generated by Django 2.2.6 on 2019-10-20 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lookspace_app', '0003_schedulevisit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedulevisit',
            old_name='comapny_name',
            new_name='company_name',
        ),
    ]
