# Generated by Django 2.2.6 on 2019-10-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookspace_app', '0004_auto_20191020_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulevisit',
            name='time',
            field=models.TimeField(),
        ),
    ]
