# Generated by Django 2.2.6 on 2019-10-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookspace_app', '0005_auto_20191021_0737'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=64, null=True)),
                ('email', models.EmailField(max_length=128, null=True)),
                ('message', models.CharField(max_length=64, null=True)),
            ],
        ),
    ]
