# Generated by Django 2.2.6 on 2019-10-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookspace_app', '0006_contactform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacedetails',
            name='time',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
